# Data visualization: homework 1
By: Khrystyna Kubatska

#### Import required libraries

In [3]:
from IPython.display import IFrame

In [4]:
#IFrame(src='https://www.nytimes.com/interactive/2018/01/18/climate/hottest-year-2017.html', width=1200, height=550)

In [5]:
import pandas as pd
import altair as alt

#### Read data

In [6]:
df = pd.read_csv('GLB.Ts_dSST.csv', skiprows=[0])
df.head()

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON
0,1880,-0.29,-0.18,-0.11,-0.19,-0.11,-0.23,-0.21,-0.09,-0.16,-0.23,-0.20,-0.23,-0.19,***,***,-0.14,-0.18,-0.20
1,1881,-0.15,-0.17,0.04,0.04,0.02,-0.20,-0.06,-0.02,-0.13,-0.20,-0.21,-0.10,-0.10,-.11,-.18,0.03,-0.09,-0.18
2,1882,0.15,0.15,0.04,-0.18,-0.16,-0.26,-0.20,-0.05,-0.10,-0.24,-0.16,-0.24,-0.10,-.09,.06,-0.10,-0.17,-0.17
3,1883,-0.31,-0.39,-0.13,-0.17,-0.20,-0.12,-0.08,-0.15,-0.20,-0.14,-0.22,-0.16,-0.19,-.20,-.31,-0.16,-0.12,-0.19
4,1884,-0.15,-0.08,-0.37,-0.42,-0.36,-0.40,-0.34,-0.26,-0.27,-0.24,-0.30,-0.28,-0.29,-.28,-.13,-0.39,-0.34,-0.27

#### Data Processing

In [7]:
temp_df = df.copy()
temp_df.drop(['Year', 'J-D','D-N', 'DJF', 'MAM', 'JJA','SON'], axis = 1, inplace = True)
temp_df.head()

    Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
0 -0.29 -0.18 -0.11 -0.19 -0.11 -0.23 -0.21 -0.09 -0.16 -0.23 -0.20 -0.23
1 -0.15 -0.17  0.04  0.04  0.02 -0.20 -0.06 -0.02 -0.13 -0.20 -0.21 -0.10
2  0.15  0.15  0.04 -0.18 -0.16 -0.26 -0.20 -0.05 -0.10 -0.24 -0.16 -0.24
3 -0.31 -0.39 -0.13 -0.17 -0.20 -0.12 -0.08 -0.15 -0.20 -0.14 -0.22 -0.16
4 -0.15 -0.08 -0.37 -0.42 -0.36 -0.40 -0.34 -0.26 -0.27 -0.24 -0.30 -0.28

In [8]:
df['average_temp'] = temp_df.mean(axis = 1)
# df.head()

In [9]:
df1 = df.copy()
df1.drop(['J-D','D-N', 'DJF', 'MAM', 'JJA','SON', 
          'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
         , axis = 1, inplace = True)
df1.head()

   Year  average_temp
0  1880     -0.185833
1  1881     -0.095000
2  1882     -0.104167
3  1883     -0.189167
4  1884     -0.289167

## Chart

In [10]:
main_chart = alt.Chart(df1).mark_point(
    
            color = '#404040', fill = '#f06400',
            size = 90, opacity = 1, strokeWidth = 1
            ).encode(
    
    x = alt.X(field='Year', type = 'quantitative', title='',
              scale = alt.Scale(zero = False),
              axis = alt.Axis(format = 'k', tickCount = 13, labelFontSize=13, labelColor='#b3b3b3')),
    
    y = alt.Y(field = 'average_temp', type = 'quantitative', title='',
              scale = alt.Scale(zero = False),
              axis = alt.Axis(tickCount = 10, labelFontSize=13, labelColor = '#b3b3b3'))
)


zero_line = alt.Chart(pd.DataFrame({'y': [0]})).mark_rule(color='#A9A9A9').encode(y='y')


title_upper_text = alt.Chart({'values':[{'x': 1883, 'y': 0.93}]}
                            ).mark_text(
                                text='Annual Global Surface Temperature,', 
                                align='left', fontSize=15, fontWeight=800
                            ).encode(x='x:quantitative', y='y:quantitative')

title_bottom_text = alt.Chart({'values':[{'x': 1883, 'y': 0.87}]}
                             ).mark_text(
                                text='Relative to Late 19th Century Average',
                                align='left', fontSize=15, fontWeight=800
                             ).encode( x='x:quantitative', y='y:quantitative')


right_upper_text = alt.Chart({'values':[{'x': 2017, 'y': 0.13}]}
                            ).mark_text(
                                text='HOTTER THAN THE', align='right', 
                                fontWeight=500
                            ).encode( x='x:quantitative', y='y:quantitative')

right_middle_text = alt.Chart({'values':[{'x': 2017, 'y': 0.07}]}
                            ).mark_text(
                                text='1880-1899 AVERAGE', align='right',
                                fontWeight=500
                            ).encode( x='x:quantitative', y='y:quantitative')

right_bottom_text = alt.Chart({'values':[{'x': 2017, 'y': -0.07}]}
                            ).mark_text(
                                align='right',
                                text='COLDER',
                                fontWeight=500
                            ).encode( x='x:quantitative', y='y:quantitative')


years = [1904, 1944, 1998, 2014, 2015, 2016, 2017]
years_var = [0, 0, 0, 0, 0, 0, 0]
    
for i in range(len(years)):
    years_var[i] = alt.Chart({'values':[{'x': years[i]-1, 
                                         'y': df1._get_value(df1.index[df1['Year']==years[i]].tolist()[0], 'average_temp')}]}
                        ).mark_text(
                            align='right', text=str(years[i]),
                            fontWeight=500, fontSize=15,
                            ).encode( x='x:quantitative', y='y:quantitative')


alt.layer(main_chart, zero_line, 
              title_upper_text, title_bottom_text, 
              right_upper_text, right_middle_text, right_bottom_text,
              years_var[0], years_var[1], years_var[2], years_var[3], 
              years_var[4], years_var[5], years_var[6]
         ).properties(width = 900, height = 500, background = '#F9F9F9', padding = 25
         ).configure_axis(ticks = False, domain = False)

alt.LayerChart(...)

#### Main issues:  
   1. Fonts and colors
   2. Displaying '+'/'-' and '°' for temperature
      (degree_sign = u'\N{DEGREE SIGN}' -> Javascript Error: Expression parse error: (°))
   3. Displaying years text
   4. 'Years' and 'Without El Niño' buttons